### ISSUE TITLE
1.0.0-RC5 cannot be added to .Net Framework 4.5.2 project

### ISSUE THREAD

**Issue by Zshazz** [naasking/Dapper.Compose#1]
It's worth noting that 1.0.0-RC1 installs successfully.

# Repro steps

1. Open VS2017
2. Create new MVC Project using .NET Framework 4.5.2

![image](https://cloud.githubusercontent.com/assets/1164057/25196522/f5c3b0c4-250e-11e7-91bb-01e9398643b4.png)

3. Use MVC Template:

![image](https://cloud.githubusercontent.com/assets/1164057/25196564/1084afee-250f-11e7-98fe-e9f87d3bbfff.png)

4. Install Dapper via `Install-Package Dapper` (works fine)

![image](https://cloud.githubusercontent.com/assets/1164057/25196659/48549254-250f-11e7-85cb-a3d4e1eb0fce.png)

5. Install Dapper.Compose via `install-package Dapper.Compose -pre`
   (fails with error ```
install-package : Could not install package 'Dapper.Compose 1.0.0-RC5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any 
assembly references or content files that are compatible with that framework. For more information, contact the package author.```)

![image](https://cloud.githubusercontent.com/assets/1164057/25196762/a5f9520a-250f-11e7-8f43-d4f968f9bc12.png)

# Workaround

Use `Install-Package Dapper.Compose -pre -Version 1.0.0-RC1`

![image](https://cloud.githubusercontent.com/assets/1164057/25196816/d0f1811c-250f-11e7-8b9e-0c4e316aa855.png)

Thank you for your time,
Chris

**Comment by naasking** [comment]
I switched to target .NET standard 1.3 in later RCs (same as Dapper), which only supports .NET 4.6 or higher and .NET core. It'd be great to target lower versions too, but I hate wrestling with build systems or writing build scripts, which seems like it would be necessary from what I see in Dapper's repo. If you have a suggestion for how to do this easily I'm all ears! I'll mark this as an enhancement until I get to it or someone else contributes this.

**Comment by nrcmkoh** [comment]
I had the same issue, so I installed v1.0.0-RC1, but the Load extension method is missing in this version.

**Comment by naasking** [comment]
I've changed the latest release to target multiple .NEt frameworks and multiple .NET standards, including .NET 4.5.2.
