### ISSUE TITLE
Index out of bounds exception if you have sql code with just one char in one line.

### ISSUE THREAD

**Issue by svedaker** [naasking/Dapper.Compose#2]
>INSERT INTO [WS].[ProductChannelProperty] (
        ProductIntegrationKey, 
        ChannelIntegrationKey
    VALUES(
        @ProductIntegrationKey,
        @ChannelIntegrationKey
    )

This sql code will give a "index out of bounds" exception in Query.Load when you read the last line with ")" and try to check if it's a comment looking for "--" (looking at line[1] which don't exists)

**Comment by naasking** [comment]
Thanks for the bug report. I pushed this fix and a few other enhancements I've made into another nuget release.

**Comment by svedaker** [comment]
Now I get an System.Data.SqlClient.SqlException : Incorrect syntax instead. The row with ")" is missing from the query.

**Comment by naasking** [comment]
Sorry about that, fixed.
